//
// File Autogenerated by SaltyPaw's PNG conversion script
//
//


#include "bitmaps.h"
#include "ocpn_plugin.h"
//
wxBitmap _img_exp_sq;
wxBitmap _img_oil_rig;
wxBitmap _img_sector;
wxBitmap _img_sector_uscg;
wxBitmap _img_trackln_both;
wxBitmap _img_trackln1;
wxBitmap _img_trackln1_port;
//
void initialize_bitmaps(void)
{
    wxFileName fn;
    wxString path = GetPluginDataDir("sar_pi");
    fn.SetPath(path);
    fn.AppendDir("data");
    fn.AppendDir("bitmaps");

    fn.SetFullName("exp_sq.png");
    path = fn.GetFullPath();
    wxImage panelIcon(path);
    _img_exp_sq = wxBitmap(panelIcon);

    fn.SetFullName("oil_rig.png");
    path = fn.GetFullPath();
    wxImage panelIcon1(path);
    _img_oil_rig = wxBitmap(panelIcon1);

    fn.SetFullName("sector.png");
    path = fn.GetFullPath();
    wxImage panelIcon2(path);
    _img_sector = wxBitmap(panelIcon2);

    fn.SetFullName("sector_uscg.png");
    path = fn.GetFullPath();
    wxImage panelIcon3(path);
    _img_sector_uscg = wxBitmap(panelIcon3);

    fn.SetFullName("trackln_both.png");
    path = fn.GetFullPath();
    wxImage panelIcon4(path);
    _img_trackln_both = wxBitmap(panelIcon4);

    fn.SetFullName("trackln1.png");
    path = fn.GetFullPath();
    wxImage panelIcon5(path);
    _img_trackln1 = wxBitmap(panelIcon5);

    fn.SetFullName("trackln1_port.png");
    path = fn.GetFullPath();
    wxImage panelIcon6(path);
    _img_trackln1_port = wxBitmap(panelIcon6);
  
    return;
}
